sudo: false

language: python
python:
  - "3.5"
  - "2.7"

install:
    - travis_retry pip install tox
script:
    - TOX_ENVIRONMENT="py${TRAVIS_PYTHON_VERSION//./}"
    - tox -e "$TOX_ENVIRONMENT"
after_success:
    - if [[ $TOX_ENVIRONMENT == 'py35' ]] ; then tox -e py35-coveralls; else echo "No coverage to do"; fi
